In [8]:
import pandas as pd
import numpy as np
file = '/home/ishida/OneDrive/2023/class/大学院/A000010_shussekibo_group.xlsx'
dat = pd.read_csv(file)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 12: invalid continuation byte

In [10]:
with open(file,mode="rb") as excel_file:
    df = pd.read_excel(file)

In [11]:
df.head()

   Unnamed: 0        所属        学生番号     氏名       フリガナ  年次
0           1  創成Ｍ　地域創成  1023450016  河見　竜摩    ｶﾜﾐ ﾀﾂﾏ  1年
1           2  創成Ｍ　地域創成  1023450025  永本　智富  ﾅｶﾞﾓﾄ  ﾁﾌ  1年
2           3  創成Ｍ　地域創成  1023450034  内海　裕也    ｳﾂﾐ ﾕｳﾔ  1年
3           4  創成Ｍ　地域創成  1023450052   沈　思宁     ｼﾝ ｼﾈｲ  1年
4           5  創成Ｍ　地域創成  1023450061  山下　美奈    ﾔﾏｼﾀ ﾐﾅ  1年

In [14]:
## calculate modulo 9 of index and set this as a new column
df['group'] = df.index % 9

In [16]:
df.head()

   Unnamed: 0        所属        学生番号     氏名       フリガナ  年次  group
0           1  創成Ｍ　地域創成  1023450016  河見　竜摩    ｶﾜﾐ ﾀﾂﾏ  1年      0
1           2  創成Ｍ　地域創成  1023450025  永本　智富  ﾅｶﾞﾓﾄ  ﾁﾌ  1年      1
2           3  創成Ｍ　地域創成  1023450034  内海　裕也    ｳﾂﾐ ﾕｳﾔ  1年      2
3           4  創成Ｍ　地域創成  1023450052   沈　思宁     ｼﾝ ｼﾈｲ  1年      3
4           5  創成Ｍ　地域創成  1023450061  山下　美奈    ﾔﾏｼﾀ ﾐﾅ  1年      4

In [31]:
df_shuffled = df.groupby('group').apply(lambda x: x.sample(frac=1)).reset_index(drop=True)

In [41]:
# divide rows into groups and randomly shuffle them and set numbers within each group and save to a new dataframe
df_shuffled['number'] = df_shuffled.groupby('group').cumcount()+1 
df_shuffled['number'] = df_shuffled['number'] % 7 + 1

In [42]:
df_shuffled.head(10)

,Unnamed: 0,所属,学生番号,氏名,フリガナ,年次,group,number
0,96,創成Ｍ 理工 機械・修士,6123320176,安田 澪平,ﾔｽﾀﾞ ﾘｮｳﾍｲ,1年,0,2
1,28,創成Ｍ 臨床心理,1023460120,麻植 義喜,ｵｴ ﾖｼｷ,1年,0,3
2,305,創成Ｍ 理工 知能・修士,6123350362,LIU YUPU,ﾘｭｳ ｳﾊｸ,1年,0,4
3,105,創成Ｍ 理工 機械・修士,6123320265,大西 亮輔,ｵｵﾆｼ ﾘｮｳｽｹ,1年,0,5
4,369,創成Ｍ 生物資源 生命・修士,7023310061,中杉 昌太,ﾅｶｽｷﾞ ｼｮｳﾀ,1年,0,6
5,396,創成Ｍ 生物資源 食料・修士,7023320111,藤田 智帆,ﾌｼﾞﾀ ﾁﾎ,1年,0,7
6,296,創成Ｍ 理工 知能・修士,6123350273,中道 紀志,ﾅｶﾐﾁ ﾄｼﾕｷ,1年,0,1
7,314,創成Ｍ 理工 知能・修士,6123350461,山本 郷平,ﾔﾏﾓﾄ ｷｮｳﾍｲ,1年,0,2
8,323,創成Ｍ 理工 光・修士,6123360019,大久保 雄世,ｵｵｸﾎﾞ ﾕｳｾｲ,1年,0,3
9,10,創成Ｍ 地域創成,1023450114,郑 梦真,ﾃｰ ﾑｼﾝ,1年,0,4

In [36]:
df_shuffled.sort_values(by=['group', 'number'], inplace=True)

In [37]:
df_shuffled.to_excel('A000010_shussekibo_group_shuffled.xlsx', index=False)

In [24]:
grouped = df_shuffled.groupby('group')
for group in grouped.groups:
    print(group)
    # print(grouped.get_group(group), "\n")
    grouped = group.groupby('number').cumcount()+1
    grouped.get_group(group).to_csv("group_" + str(group) + ".csv", index=False)

0

AttributeError: 'int' object has no attribute 'groupby'

In [17]:
# divide rows into groups and save each group as a new dataframe
grouped = df.groupby('group')
for group in grouped.groups:
    print(group)
    print(grouped.get_group(group), "\n")
    grouped.get_group(group).to_csv("group_" + str(group) + ".csv", index=False)

0
     Unnamed: 0              所属        学生番号        氏名        フリガナ  年次  group
0             1        創成Ｍ　地域創成  1023450016     河見　竜摩     ｶﾜﾐ ﾀﾂﾏ  1年      0
9            10        創成Ｍ　地域創成  1023450114      郑　梦真      ﾃｰ ﾑｼﾝ  1年      0
18           19        創成Ｍ　臨床心理  1023460031     上埜　勇登     ｳｴﾉ ﾕｳﾄ  1年      0
27           28        創成Ｍ　臨床心理  1023460120     麻植　義喜      ｵｴ ﾖｼｷ  1年      0
36           39    創成Ｍ　理工　化学・修士  6122330481      張　友政    ﾁｮｳ ﾕｳｾｲ  1年      0
45           50    創成Ｍ　理工　社会・修士  6123310071     丸田　康平    ﾏﾙﾀ ｺｳﾍｲ  1年      0
54           59    創成Ｍ　理工　社会・修士  6123310161     高山　昌士    ﾀｶﾔﾏ ﾏｻｼ  1年      0
63           68    創成Ｍ　理工　社会・修士  6123310250     長井　悠真    ﾅｶﾞｲ ﾕｳﾏ  1年      0
72           77    創成Ｍ　理工　社会・修士  6123310349     前川　蒼太   ﾏｴｶﾞﾜ ｿｳﾀ  1年      0
81           86    創成Ｍ　理工　機械・修士  6123320078     金谷　上太   ｶﾅﾔ ｼﾞｮｳﾀ  1年      0
90           96    創成Ｍ　理工　機械・修士  6123320176     安田　澪平  ﾔｽﾀﾞ ﾘｮｳﾍｲ  1年      0
99          105    創成Ｍ　理工　機械・修士  6123320265     大西　亮輔  ｵｵﾆｼ ﾘｮｳｽｹ  1年      0
108         114    創成Ｍ　理工　機械・修士  6123320354    塩田　雄一郎  ｼｵﾀ ﾕｳｲﾁﾛｳ  1年      0
117         123    創成Ｍ　理工　機械・修士  6123320443     角野　友梧    ｶｸﾉ ﾕｳｺﾞ  1年      0
126         133    創成Ｍ　理工　機械・修士  6123320541     櫻井　雄弥    ｻｸﾗｲ ﾕｳﾔ  1年      0
135         142    創成Ｍ　理工　機械・修士  6123320631      平野　輝     ﾋﾗﾉ ﾋｶﾙ  1年      0
144         151    創成Ｍ　理工　機械・修士  6123320720     大槻　智一  ｵｵﾂｷ ﾄﾓｶｽﾞ  1年      0
153         160    創成Ｍ　理工　化学・修士  6123330065    三好　亮太朗  ﾐﾖｼ ﾘｮｳﾀﾛｳ  1年      0
162         170    創成Ｍ　理工　化学・修士  6123330163       原　匠      ﾊﾗ ﾀｸﾐ  1年      0
171         179    創成Ｍ　理工　化学・修士  6123330252     岩井　大輝     ｲﾜｲ ﾀｲｷ  1年      0
180         188    創成Ｍ　理工　化学・修士  6123330341     髙杉　海慶   ﾀｶｽｷﾞ ﾐﾉﾘ  1年      0
189         197    創成Ｍ　理工　化学・修士  6123330431     喜多　佑輔     ｷﾀ ﾕｳｽｹ  1年      0
198         206    創成Ｍ　理工　電気・修士  6123340052     佐々木　渓      ｻｻｷ ｹｲ  1年      0
207         215    創成Ｍ　理工　電気・修士  6123340141    小山田　瑞季  ｵﾔﾏﾀﾞ ﾐｽﾞｷ  1年      0
216         224    創成Ｍ　理工　電気・修士  6123340231      孫　千誠   ｿﾝ ﾁｪﾝﾁｮﾝ  1年      0
225         233    創成Ｍ　理工　電気・修士  6123340320    山形　ひとみ   ﾔﾏｶﾞﾀ ﾋﾄﾐ  1年      0
234         242    創成Ｍ　理工　電気・修士  6123340419     川上　拓哉    ｶﾜｶﾐ ﾀｸﾔ  1年      0
243         251    創成Ｍ　理工　電気・修士  6123340508     竹下　立晟  ﾀｹｼﾀ ﾘｭｳｾｲ  1年      0
252         260    創成Ｍ　理工　電気・修士  6123340590     三木　勇人      ﾐｷ ﾊﾔﾄ  1年      0
261         269    創成Ｍ　理工　電気・修士  6123340689     川口　大貴  ｶﾜｸﾞﾁ ﾋﾛﾀｶ  1年      0
270         278    創成Ｍ　理工　知能・修士  6123350086     伊達　龍斗    ﾀﾞﾃ ﾘｭｳﾄ  1年      0
279         287    創成Ｍ　理工　知能・修士  6123350184     松尾　泰成    ﾏﾂｵ ﾀｲｾｲ  1年      0
288         296    創成Ｍ　理工　知能・修士  6123350273     中道　紀志   ﾅｶﾐﾁ ﾄｼﾕｷ  1年      0
297         305    創成Ｍ　理工　知能・修士  6123350362  LIU YUPU     ﾘｭｳ ｳﾊｸ  1年      0
306         314    創成Ｍ　理工　知能・修士  6123350461     山本　郷平  ﾔﾏﾓﾄ ｷｮｳﾍｲ  1年      0
315         323     創成Ｍ　理工　光・修士  6123360019    大久保　雄世  ｵｵｸﾎﾞ ﾕｳｾｲ  1年      0
324         333     創成Ｍ　理工　光・修士  6123360117     永山　寛太   ﾅｶﾞﾔﾏ ｶﾝﾀ  1年      0
333         342     創成Ｍ　理工　光・修士  6123360206     宗實　晃輝   ﾑﾈｻﾞﾈ ｺｳｷ  1年      0
342         351    創成Ｍ　理工　自然・修士  6123380011     福井　翔輝    ﾌｸｲ ｼｮｳｷ  1年      0
351         360    創成Ｍ　理工　自然・修士  6123380101      中井　花      ﾅｶｲ ﾊﾅ  1年      0
360         369  創成Ｍ　生物資源　生命・修士  7023310061     中杉　昌太  ﾅｶｽｷﾞ ｼｮｳﾀ  1年      0
369         378  創成Ｍ　生物資源　生命・修士  7023310151    佐々木　蒼斗     ｻｻｷ ｱｵﾄ  1年      0
378         387  創成Ｍ　生物資源　食料・修士  7023320021     前田　竜瑚  ﾏｴﾀﾞ ﾘｮｳｺﾞ  1年      0
387         396  創成Ｍ　生物資源　食料・修士  7023320111     藤田　智帆     ﾌｼﾞﾀ ﾁﾎ  1年      0
396         405  創成Ｍ　生物資源　食料・修士  7023320200     平林　仁希   ﾋﾗﾊﾞﾔｼ ﾆｷ  1年      0

1
     Unnamed: 0              所属        学生番号          氏名         フリガナ  年次  \
1             2        創成Ｍ　地域創成  1023450025       永本　智富    ﾅｶﾞﾓﾄ  ﾁﾌ  1年
10           11        創成Ｍ　地域創成  1023450123       武市　秀男   ﾀｹｲﾁ  ﾋﾃﾞｵ  1年
19           20        創成Ｍ　臨床心理  1023460040        安治　亘     ｱﾝｼﾞ ﾜﾀﾙ  1年
28           29        創成Ｍ　臨床心理  1023460139       井原　奈桜       ｲﾊﾗ ﾅｵ  1年
37           40    創成Ｍ　理工　知能・修士  6122350608        唐　雄飛       ﾄｳ ﾕｳﾋ  1年
46           51    創成Ｍ　理工　社会・修士  6123310081       岡本　拓巳     ｵｶﾓﾄ ﾀｸﾐ  1年
55           60    創成Ｍ　理工　社会・修士  6123310170       高名　柚衣       ﾀｶﾅ ﾕｲ  1年
64           69    創成Ｍ　理工　社会・修士  6123310269       天羽　翔栄    ｱﾓｳ ｼｮｳｴｲ  1年
73           78    創成Ｍ　理工　社会・修士  6123310358       渡邉　映心   ﾜﾀﾅﾍﾞ ｴｲｼﾝ  1年
82           87    創成Ｍ　理工　機械・修士  6123320087       檜垣　将之    ﾋｶﾞｷ ﾏｻﾕｷ  1年
91           97    創成Ｍ　理工　機械・修士  6123320185        堀川　凌     ﾎﾘｶﾜ ﾘｮｳ  1年
100         106    創成Ｍ　理工　機械・修士  6123320274       吉田　雄貴     ﾖｼﾀﾞ ﾕｳｷ  1年
109         115    創成Ｍ　理工　機械・修士  6123320363       田中　秀明    ﾀﾅｶ ﾋﾃﾞｱｷ  1年
118         124    創成Ｍ　理工　機械・修士  6123320452       平井　嵩馬     ﾋﾗｲ ｼｭｳﾏ  1年
127         134    創成Ｍ　理工　機械・修士  6123320551       北川　温基    ｷﾀｶﾞﾜ ﾊﾙｷ  1年
136         143    創成Ｍ　理工　機械・修士  6123320640        湯川　宙       ﾕｶﾜ ｿﾗ  1年
145         152    創成Ｍ　理工　機械・修士  6123320739       塩田　晃大     ｼｵﾀ ｱｷﾋﾛ  1年
154         161    創成Ｍ　理工　化学・修士  6123330074       福永　竜星  ﾌｸﾅｶﾞ ﾘｭｳｾｲ  1年
163         171    創成Ｍ　理工　化学・修士  6123330172       蜂谷　龍浩     ﾊﾁﾔ ﾀﾂﾋﾛ  1年
172         180    創成Ｍ　理工　化学・修士  6123330261       西村　海人     ﾆｼﾑﾗ ｶｲﾄ  1年
181         189    創成Ｍ　理工　化学・修士  6123330351       松山　晃大    ﾏﾂﾔﾏ ｱｷﾋﾛ  1年
190         198    創成Ｍ　理工　化学・修士  6123330440       鳥井　優花      ﾄﾘｲ ﾕｳｶ  1年
199         207    創成Ｍ　理工　電気・修士  6123340061       大山　泰史    ｵｵﾔﾏ ﾔｽﾌﾐ  1年
208         216    創成Ｍ　理工　電気・修士  6123340151       野本　和希     ﾉﾓﾄ ｶｽﾞｷ  1年
217         225    創成Ｍ　理工　電気・修士  6123340240       後藤　海翔     ｺﾞﾄｳ ｶｲﾄ  1年
226         234    創成Ｍ　理工　電気・修士  6123340339       古田　俊輔    ﾌﾙﾀ ｼｭﾝｽｹ  1年
235         243    創成Ｍ　理工　電気・修士  6123340428       須藤　直也      ｽﾄｳ ﾅｵﾔ  1年
244         252    創成Ｍ　理工　電気・修士  6123340517      古川　智和人     ﾌﾙｶﾜ ﾁｶﾄ  1年
253         261    創成Ｍ　理工　電気・修士  6123340606       岡　良太    ｶﾀｵｶ ﾘｮｳﾀ  1年
262         270    創成Ｍ　理工　電気・修士  6123340698       木村　智也      ｷﾑﾗ ﾄﾓﾔ  1年
271         279    創成Ｍ　理工　知能・修士  6123350101       藤原　大輝   ﾌｼﾞﾜﾗ ﾀﾞｲｷ  1年
280         288    創成Ｍ　理工　知能・修士  6123350193  LYU JUNCEN      ﾛ ｼｭﾝｼﾝ  1年
289         297    創成Ｍ　理工　知能・修士  6123350282        王　博源     ｵｳ ﾊｸｹﾞﾝ  1年
298         306    創成Ｍ　理工　知能・修士  6123350371       中川　透舞    ﾅｶｶﾞﾜ ﾄｳﾏ  1年
307         315    創成Ｍ　理工　知能・修士  6123350470       髙橋　孝輔    ﾀｶﾊｼ ｺｳｽｹ  1年
316         324     創成Ｍ　理工　光・修士  6123360028       中西　康介    ﾅｶﾆｼ ｺｳｽｹ  1年
325         334     創成Ｍ　理工　光・修士  6123360126      小関　慎之助   ｵｾﾞｷ ｼﾝﾉｽｹ  1年
334         343     創成Ｍ　理工　光・修士  6123360215       上田　柊斗    ｳｴﾀﾞ ｼｭｳﾄ  1年
343         352    創成Ｍ　理工　自然・修士  6123380021       廣田　翔也     ﾋﾛﾀ ｼｮｳﾔ  1年
352         361    創成Ｍ　理工　自然・修士  6123380110       西井　陸人      ﾆｼｲ ﾘｸﾄ  1年
361         370  創成Ｍ　生物資源　生命・修士  7023310071       青山　里菜      ｱｵﾔﾏ ﾘﾅ  1年
370         379  創成Ｍ　生物資源　生命・修士  7023310160       松岡　颯大     ﾏﾂｵｶ ｿｳﾀ  1年
379         388  創成Ｍ　生物資源　食料・修士  7023320031      木内　かなえ     ｷﾉｳﾁ ｶﾅｴ  1年
388         397  創成Ｍ　生物資源　食料・修士  7023320120       橋村　寧々      ﾊｼﾑﾗ ﾈﾈ  1年
397         406  創成Ｍ　生物資源　食料・修士  7023320219       山西　百音      ﾔﾏﾆｼ ﾓﾈ  1年

     group
1        1
10       1
19       1
28       1
37       1
46       1
55       1
64       1
73       1
82       1
91       1
100      1
109      1
118      1
127      1
136      1
145      1
154      1
163      1
172      1
181      1
190      1
199      1
208      1
217      1
226      1
235      1
244      1
253      1
262      1
271      1
280      1
289      1
298      1
307      1
316      1
325      1
334      1
343      1
352      1
361      1
370      1
379      1
388      1
397      1

2
     Unnamed: 0              所属        学生番号              氏名           フリガナ  \
2             3        創成Ｍ　地域創成  1023450034           内海　裕也        ｳﾂﾐ ﾕｳﾔ
11           12        創成Ｍ　地域創成  1023450132       PU LINGYI         ﾌ ﾚｲｴｷ
20           21        創成Ｍ　臨床心理  1023460059          長谷川　大吾    ﾊｾｶﾞﾜ ﾀﾞｲｺﾞ
29           30    創成Ｍ　理工　機械・修士  6122320206           塩津　圭汰        ｼｵﾂ ｹｲﾀ
38           41     創成Ｍ　理工　光・修士  6122360284           太田　夏規        ｵｵﾀ ﾅﾂｷ
47           52    創成Ｍ　理工　社会・修士  6123310090          秋月　淳之介  ｱｷﾂﾞｷ ｼﾞｭﾝﾉｽｹ
56           61    創成Ｍ　理工　社会・修士  6123310189           楠本　竜生       ｸｽﾓﾄ ﾀﾂｷ
65           70    創成Ｍ　理工　社会・修士  6123310278           松尾　優輝        ﾏﾂｵ ﾕｳｷ
74           79    創成Ｍ　理工　社会・修士  6123310367            任　林蔚        ﾆﾝ ﾘﾝｴｲ
83           88    創成Ｍ　理工　機械・修士  6123320096            濵本　楽        ﾊﾏﾓﾄ ﾗｸ
92           98    創成Ｍ　理工　機械・修士  6123320194           辻元　優作     ﾂｼﾞﾓﾄ ﾕｳｻｸ
101         107    創成Ｍ　理工　機械・修士  6123320283           瀬岡　皆人        ｾｵｶ ｶｲﾄ
110         116    創成Ｍ　理工　機械・修士  6123320372           宗和　亮汰       ｿｳﾜ ﾘｮｳﾀ
119         126    創成Ｍ　理工　機械・修士  6123320471           明樂　春樹      ﾐﾖｳﾗｸ ﾊﾙｷ
128         135    創成Ｍ　理工　機械・修士  6123320560          大久保　直哉      ｵｵｸﾎﾞ ﾅｵﾔ
137         144    創成Ｍ　理工　機械・修士  6123320659           山地　広大     ﾔﾏｼﾞ ｺｳﾀﾞｲ
146         153    創成Ｍ　理工　機械・修士  6123320748            藤原　暢      ﾌｼﾞﾜﾗ ｲﾀﾙ
155         162    創成Ｍ　理工　化学・修士  6123330083           新居　源也         ﾆｲ ﾓﾄﾔ
164         172    創成Ｍ　理工　化学・修士  6123330181            邱　政維        ｷｭｳ ｾｲｲ
173         181    創成Ｍ　理工　化学・修士  6123330271           竹田　大登       ﾀｹﾀﾞ ﾋﾛﾄ
182         190    創成Ｍ　理工　化学・修士  6123330360           石丸　直輝       ｲｼﾏﾙ ﾅｵｷ
191         199    創成Ｍ　理工　化学・修士  6123330459           土塔　悟司       ﾄﾞﾄｳ ｻﾄｼ
200         208    創成Ｍ　理工　電気・修士  6123340071          宇都宮　立樹      ｳﾂﾉﾐﾔ ﾘﾂｷ
209         217    創成Ｍ　理工　電気・修士  6123340160           赤松　大地      ｱｶﾏﾂ ﾀﾞｲﾁ
218         226    創成Ｍ　理工　電気・修士  6123340259           小郷　和樹      ｵｺﾞｳ ｶｽﾞｷ
227         235    創成Ｍ　理工　電気・修士  6123340348           福谷　友基       ﾌｸﾀﾆ ﾄﾓｷ
236         244    創成Ｍ　理工　電気・修士  6123340437           川田　達哉       ｶﾜﾀﾞ ﾀﾂﾔ
245         253    創成Ｍ　理工　電気・修士  6123340526           東本　昂大    ﾋｶﾞｼﾓﾄ ﾀｶﾋﾛ
254         262    創成Ｍ　理工　電気・修士  6123340615           松岡　敦嗣       ﾏﾂｵｶ ｱﾂｼ
263         271    創成Ｍ　理工　知能・修士  6123350012            奥田　亮       ｵｸﾀﾞ ﾘｮｳ
272         280    創成Ｍ　理工　知能・修士  6123350111           齊藤　雅門       ｻｲﾄｳ ﾏｻﾄ
281         289    創成Ｍ　理工　知能・修士  6123350200           山本　賢典      ﾔﾏﾓﾄ ｹﾝｽｹ
290         298    創成Ｍ　理工　知能・修士  6123350291           米澤　源太     ﾖﾈｻﾞﾜ ｹﾞﾝﾀ
299         307    創成Ｍ　理工　知能・修士  6123350381           石垣　龍人     ｲｼｶﾞｷ ﾘｭｳﾄ
308         316    創成Ｍ　理工　知能・修士  6123350489           巨島　弘基       ｺｼﾞﾏ ﾋﾛｷ
317         326     創成Ｍ　理工　光・修士  6123360046          中村　亜友佳       ﾅｶﾑﾗ ｱﾕｶ
326         335     創成Ｍ　理工　光・修士  6123360135           柚山　俊介      ﾕﾔﾏ ｼｭﾝｽｹ
335         344     創成Ｍ　理工　光・修士  6123360224           以倉　優一       ｲｸﾗ ﾕｳｲﾁ
344         353    創成Ｍ　理工　自然・修士  6123380030            櫻井　樹        ｻｸﾗｲ ﾐｷ
353         362    創成Ｍ　理工　自然・修士  6123380129           岸本　桃弥       ｷｼﾓﾄ ﾄｳﾔ
362         371  創成Ｍ　生物資源　生命・修士  7023310080           山森　優護      ﾔﾏﾓﾘ ﾕｳｺﾞ
371         380  創成Ｍ　生物資源　生命・修士  7023310179  DINH GIA THIEN   ﾃﾞｨﾝ ｻﾞ ﾃｨｴﾝ
380         389  創成Ｍ　生物資源　食料・修士  7023320040           宮崎　さほ       ﾐﾔｻﾞｷ ｻﾎ
389         398  創成Ｍ　生物資源　食料・修士  7023320139          玉井　明日香        ﾀﾏｲ ｱｽｶ
398         407  創成Ｍ　生物資源　生産・修士  7023330019          鳥越　菜々花      ﾄﾘｺﾞｴ ﾅﾅｶ

     年次  group
2    1年      2
11   1年      2
20   1年      2
29   2年      2
38   1年      2
47   1年      2
56   1年      2
65   1年      2
74   1年      2
83   1年      2
92   1年      2
101  1年      2
110  1年      2
119  1年      2
128  1年      2
137  1年      2
146  1年      2
155  1年      2
164  1年      2
173  1年      2
182  1年      2
191  1年      2
200  1年      2
209  1年      2
218  1年      2
227  1年      2
236  1年      2
245  1年      2
254  1年      2
263  1年      2
272  1年      2
281  1年      2
290  1年      2
299  1年      2
308  1年      2
317  1年      2
326  1年      2
335  1年      2
344  1年      2
353  1年      2
362  1年      2
371  1年      2
380  1年      2
389  1年      2
398  1年      2

3
     Unnamed: 0              所属        学生番号      氏名         フリガナ  年次  group
3             4        創成Ｍ　地域創成  1023450052    沈　思宁       ｼﾝ ｼﾈｲ  1年      3
12           13        創成Ｍ　地域創成  1023450141   原田　有理      ﾊﾗﾀﾞ ﾕﾘ  1年      3
21           22        創成Ｍ　臨床心理  1023460068   仁義　優里     ｼﾞﾝｷﾞ ﾕﾘ  1年      3
30           31    創成Ｍ　理工　化学・修士  6122330015   岩城　昂尚     ｲﾜｷ ﾀｶﾋｻ  2年      3
39           44    創成Ｍ　理工　社会・修士  6123310017   安藤　亮介  ｱﾝﾄﾞｳ ﾘｮｳｽｹ  1年      3
48           53    創成Ｍ　理工　社会・修士  6123310106   渡邉　智寛   ﾜﾀﾅﾍﾞ ﾄﾓﾋﾛ  1年      3
57           62    創成Ｍ　理工　社会・修士  6123310198   林本　鈴太    ﾊﾔｼﾓﾄ ﾚｲﾀ  1年      3
66           71    創成Ｍ　理工　社会・修士  6123310287  石田　真夢実     ｲｼﾀﾞ ﾏﾕﾐ  1年      3
75           80    創成Ｍ　理工　機械・修士  6123320013   坪井　登生     ﾂﾎﾞｲ ﾄｳｲ  1年      3
84           89    創成Ｍ　理工　機械・修士  6123320102    髙階　剛     ﾀｶｼﾅ ﾂﾖｼ  1年      3
93           99    創成Ｍ　理工　機械・修士  6123320201   岸上　颯汰     ｷｼｳｴ ｿｳﾀ  1年      3
102         108    創成Ｍ　理工　機械・修士  6123320292    別宮　壮      ﾍﾞﾂｸ ｿｳ  1年      3
111         117    創成Ｍ　理工　機械・修士  6123320381   平石　裕哉     ﾋﾗｲｼ ﾕｳﾔ  1年      3
120         127    創成Ｍ　理工　機械・修士  6123320480   串崎　聡志    ｸｼｻﾞｷ ｻﾄｼ  1年      3
129         136    創成Ｍ　理工　機械・修士  6123320579   宮本　翔太    ﾐﾔﾓﾄ ｼｮｳﾀ  1年      3
138         145    創成Ｍ　理工　機械・修士  6123320668   藤村　柊輔  ﾌｼﾞﾑﾗ ｼｭｳｽｹ  1年      3
147         154    創成Ｍ　理工　機械・修士  6123320757   澤田　朱莉     ｻﾜﾀﾞ ｱｶﾘ  1年      3
156         163    創成Ｍ　理工　化学・修士  6123330092   平井　健斗      ﾋﾗｲ ｹﾝﾄ  1年      3
165         173    創成Ｍ　理工　化学・修士  6123330191    市川　彪     ｲﾁｶﾜ ﾀｹｼ  1年      3
174         182    創成Ｍ　理工　化学・修士  6123330280   阿部　壮太      ｱﾍﾞ ｿｳﾀ  1年      3
183         191    創成Ｍ　理工　化学・修士  6123330379   生亀　浩新   ｲｷｶﾞﾒ ｺｳｼﾝ  1年      3
192         200    創成Ｍ　理工　化学・修士  6123330468   藤井　温己     ﾌｼﾞｲ ﾊﾙｷ  1年      3
201         209    創成Ｍ　理工　電気・修士  6123340080   鈴木　翔太    ｽｽﾞｷ ｼｮｳﾀ  1年      3
210         218    創成Ｍ　理工　電気・修士  6123340179   横井　宏政     ﾖｺｲ ﾋﾛﾏｻ  1年      3
219         227    創成Ｍ　理工　電気・修士  6123340268   上田　康世    ｳｴﾀﾞ ｺｳｾｲ  1年      3
228         236    創成Ｍ　理工　電気・修士  6123340357    武藤　実      ﾑﾄｳ ﾐﾉﾙ  1年      3
237         245    創成Ｍ　理工　電気・修士  6123340446   岡本　伊吹    ｵｶﾓﾄ ｲﾌﾞｷ  1年      3
246         254    創成Ｍ　理工　電気・修士  6123340535   大形　彰吾  ｵｵｶﾞﾀ ｼｮｳｺﾞ  1年      3
255         263    創成Ｍ　理工　電気・修士  6123340624   清水　空太     ｼﾐｽﾞ ｸｳﾀ  1年      3
264         272    創成Ｍ　理工　知能・修士  6123350021   大島　穂東     ｵｵｼﾏ ﾎﾂﾏ  1年      3
273         281    創成Ｍ　理工　知能・修士  6123350120   酒井　悠渡      ｻｶｲ ﾊﾙﾄ  1年      3
282         290    創成Ｍ　理工　知能・修士  6123350219  藤本　進太郎  ﾌｼﾞﾓﾄ ｼﾝﾀﾛｳ  1年      3
291         299    創成Ｍ　理工　知能・修士  6123350308   河原　寛治    ｶﾜﾊﾗ ｶﾝｼﾞ  1年      3
300         308    創成Ｍ　理工　知能・修士  6123350390   石江　悠眞      ｲｼｴ ﾕｳﾏ  1年      3
309         317    創成Ｍ　理工　知能・修士  6123350498   谷口　隼輔  ﾀﾆｸﾞﾁ ｼｭﾝｽｹ  1年      3
318         327     創成Ｍ　理工　光・修士  6123360055   伊藤　圭希      ｲﾄｳ ｹｲｷ  1年      3
327         336     創成Ｍ　理工　光・修士  6123360144   新居　蓮叶       ﾆｲ ﾚﾝﾄ  1年      3
336         345     創成Ｍ　理工　光・修士  6123360233   福田　龍弥      ﾌｸﾀ ﾀﾂﾔ  1年      3
345         354    創成Ｍ　理工　自然・修士  6123380049   渡辺　達哉    ﾜﾀﾅﾍﾞ ﾀﾂﾔ  1年      3
354         363    創成Ｍ　理工　自然・修士  6123380138   宮田　侑奈      ﾐﾔﾀ ﾕｳﾅ  1年      3
363         372  創成Ｍ　生物資源　生命・修士  7023310099   森本　華真     ﾓﾘﾓﾄ ｶｼﾝ  1年      3
372         381  創成Ｍ　生物資源　生命・修士  7023310188   𠮷野　颯真      ﾖｼﾉ ｿｳﾏ  1年      3
381         390  創成Ｍ　生物資源　食料・修士  7023320059   大畑　陽花     ｵｵﾊﾀ ﾊﾙｶ  1年      3
390         399  創成Ｍ　生物資源　食料・修士  7023320148   山田　萌加     ﾔﾏﾀﾞ ﾓｴｶ  1年      3
399         408  創成Ｍ　生物資源　生産・修士  7023330028    藤江　快      ﾌｼﾞｴ ｶｲ  1年      3

4
     Unnamed: 0              所属        学生番号      氏名         フリガナ  年次  group
4             5        創成Ｍ　地域創成  1023450061   山下　美奈      ﾔﾏｼﾀ ﾐﾅ  1年      4
13           14        創成Ｍ　地域創成  1023450151    胡　愉淇         ｺ ﾕｷ  1年      4
22           23        創成Ｍ　臨床心理  1023460077  野口　奈々夏     ﾉｸﾞﾁ ﾅﾅｶ  1年      4
31           32    創成Ｍ　理工　電気・修士  6122340399  小松原　滉人   ｺﾏﾂﾊﾞﾗ ﾋﾛﾄ  2年      4
40           45    創成Ｍ　理工　社会・修士  6123310026  元井　弘一郎   ﾓﾄｲ ｺｳｲﾁﾛｳ  1年      4
49           54    創成Ｍ　理工　社会・修士  6123310115   坂口　聡汰    ｻｶｸﾞﾁ ｿｳﾀ  1年      4
58           63    創成Ｍ　理工　社会・修士  6123310204   西條　遥稀   ｻｲｼﾞｮｳ ﾊﾙｷ  1年      4
67           72    創成Ｍ　理工　社会・修士  6123310296    上原　健      ｳｴﾊﾗ ｹﾝ  1年      4
76           81    創成Ｍ　理工　機械・修士  6123320022   松本　明彦    ﾏﾂﾓﾄ ｱｷﾋｺ  1年      4
85           90    創成Ｍ　理工　機械・修士  6123320111  妹尾　虎太郎     ｾﾉｵ ｺﾀﾛｳ  1年      4
94          100    創成Ｍ　理工　機械・修士  6123320210   菊原　拓海     ｷｸﾊﾗ ﾀｸﾐ  1年      4
103         109    創成Ｍ　理工　機械・修士  6123320309   鴨頭　勇斗   ｶﾓｶﾞｼﾗ ﾊﾔﾄ  1年      4
112         118    創成Ｍ　理工　機械・修士  6123320391   入口　知也    ｲﾘｸﾞﾁ ﾄﾓﾔ  1年      4
121         128    創成Ｍ　理工　機械・修士  6123320499   初田　直輝     ﾊﾂﾀﾞ ﾅｵｷ  1年      4
130         137    創成Ｍ　理工　機械・修士  6123320588   仙石　修平  ｾﾝｺﾞｸ ｼｭｳﾍｲ  1年      4
139         146    創成Ｍ　理工　機械・修士  6123320677   宇野　隼太      ｳﾉ ｼｭﾝﾀ  1年      4
148         155    創成Ｍ　理工　化学・修士  6123330010   小林　悠月   ｺﾊﾞﾔｼ ﾕﾂﾞｷ  1年      4
157         164    創成Ｍ　理工　化学・修士  6123330109   岡崎　拓也    ｵｶｻﾞｷ ﾀｸﾔ  1年      4
166         174    創成Ｍ　理工　化学・修士  6123330207  瀬戸　美菜萌       ｾﾄ ﾐﾅﾓ  1年      4
175         183    創成Ｍ　理工　化学・修士  6123330299   髙橋　鉄平   ﾀｶﾊｼ ﾃｯﾍﾟｲ  1年      4
184         192    創成Ｍ　理工　化学・修士  6123330388   立川　慎也     ﾀﾂｶﾜ ｼﾝﾔ  1年      4
193         201    創成Ｍ　理工　化学・修士  6123330477   宮城　乃菜      ﾐﾔｷﾞ ﾉﾅ  1年      4
202         210    創成Ｍ　理工　電気・修士  6123340099  小谷　雪之丞  ｺﾀﾆ ﾕｷﾉｼﾞｮｳ  1年      4
211         219    創成Ｍ　理工　電気・修士  6123340188   宮内　達也     ﾐﾔｳﾁ ﾀﾂﾔ  1年      4
220         228    創成Ｍ　理工　電気・修士  6123340277   三宅　偉智       ﾐﾔｹ ｲﾁ  1年      4
229         237    創成Ｍ　理工　電気・修士  6123340366   三宅　悠太      ﾐﾔｹ ﾕｳﾀ  1年      4
238         246    創成Ｍ　理工　電気・修士  6123340455   平田　真大     ﾋﾗﾀ ﾏｻﾋﾛ  1年      4
247         255    創成Ｍ　理工　電気・修士  6123340544   森本　碧唯     ﾓﾘﾓﾄ ｱｵｲ  1年      4
256         264    創成Ｍ　理工　電気・修士  6123340633   横山　雄大   ﾖｺﾔﾏ ﾕｳﾀﾞｲ  1年      4
265         273    創成Ｍ　理工　知能・修士  6123350031   根來　勇太     ﾈｺﾞﾛ ﾕｳﾀ  1年      4
274         282    創成Ｍ　理工　知能・修士  6123350139   山川　暖生     ﾔﾏｶﾜ ﾊﾙｷ  1年      4
283         291    創成Ｍ　理工　知能・修士  6123350228   早道　広峻    ﾊﾔﾐﾁ ﾋﾛﾀｶ  1年      4
292         300    創成Ｍ　理工　知能・修士  6123350317   臼井　健太      ｳｽｲ ｹﾝﾀ  1年      4
301         309    創成Ｍ　理工　知能・修士  6123350406   有賀　大貴    ｱﾘｶﾞ ﾀﾞｲｷ  1年      4
310         318    創成Ｍ　理工　知能・修士  6123350504  柏原　功太郎   ｶｼﾊﾗ ｺｳﾀﾛｳ  1年      4
319         328     創成Ｍ　理工　光・修士  6123360064  庄野　未彩季     ｼｮｳﾉ ﾐｻｷ  1年      4
328         337     創成Ｍ　理工　光・修士  6123360153   井上　友孝    ｲﾉｳｴ ﾄﾓﾀｶ  1年      4
337         346     創成Ｍ　理工　光・修士  6123360242   松田　弦大    ﾏﾂﾀﾞ ｹﾞﾝﾀ  1年      4
346         355    創成Ｍ　理工　自然・修士  6123380058   濱本　章吾   ﾊﾏﾓﾄ ｼｮｳｺﾞ  1年      4
355         364  創成Ｍ　生物資源　生命・修士  7023310016   羽原　誉幸   ﾊﾊﾞﾗ ｼｹﾞﾕｷ  1年      4
364         373  創成Ｍ　生物資源　生命・修士  7023310105   加藤　滉都      ｶﾄｳ ﾋﾛﾄ  1年      4
373         382  創成Ｍ　生物資源　生命・修士  7023310197   鶴岡　里彩      ﾂﾙｵｶ ﾘｻ  1年      4
382         391  創成Ｍ　生物資源　食料・修士  7023320068   鈴木　美里     ｽｽﾞｷ ﾐｻﾄ  1年      4
391         400  創成Ｍ　生物資源　食料・修士  7023320157   大西　陽菜      ｵｵﾆｼ ﾋﾅ  1年      4
400         409  創成Ｍ　生物資源　生産・修士  7023330037   井上　智晶    ｲﾉｳｴ ﾄﾓｱｷ  1年      4

5
     Unnamed: 0              所属        学生番号      氏名        フリガナ  年次  group
5             6        創成Ｍ　地域創成  1023450071    李　暁一    ﾘ ｷﾞｮｳｲﾁ  1年      5
14           15        創成Ｍ　地域創成  1023450160    　林      ｿﾝ ｼﾘﾝ  1年      5
23           24        創成Ｍ　臨床心理  1023460086   片山　知香    ｶﾀﾔﾏ ｻﾄｶ  1年      5
32           35     創成Ｍ　理工　光・修士  6122360041  佐々井　祐哉     ｻｻｲ ﾕｳﾔ  2年      5
41           46    創成Ｍ　理工　社会・修士  6123310035  尾幡　厚志郎  ｵﾊﾞﾀ ｺｳｼﾛｳ  1年      5
50           55    創成Ｍ　理工　社会・修士  6123310124   田邉　禎知   ﾀﾅﾍﾞ ﾖｼﾄﾓ  1年      5
59           64    創成Ｍ　理工　社会・修士  6123310213    清水　光    ｼﾐｽﾞ ﾋｶﾙ  1年      5
68           73    創成Ｍ　理工　社会・修士  6123310302   坂本　寛太    ｻｶﾓﾄ ｶﾝﾀ  1年      5
77           82    創成Ｍ　理工　機械・修士  6123320031   淺野　瑛介    ｱｻﾉ ｴｲｽｹ  1年      5
86           91    創成Ｍ　理工　機械・修士  6123320121    山上　聡   ﾔﾏｶﾞﾐ ｻﾄｼ  1年      5
95          101    創成Ｍ　理工　機械・修士  6123320229   西川　太志    ﾆｼｶﾜ ﾀｲｼ  1年      5
104         110    創成Ｍ　理工　機械・修士  6123320318   永野　博貴    ﾅｶﾞﾉ ﾋﾛｷ  1年      5
113         119    創成Ｍ　理工　機械・修士  6123320407   藤本　拓人   ﾌｼﾞﾓﾄ ﾀｸﾄ  1年      5
122         129    創成Ｍ　理工　機械・修士  6123320505  五味　弘一郎  ｺﾞﾐ ｺｳｲﾁﾛｳ  1年      5
131         138    創成Ｍ　理工　機械・修士  6123320597   藤田　健祐   ﾌｼﾞﾀ ｹﾝｽｹ  1年      5
140         147    創成Ｍ　理工　機械・修士  6123320686   仲野　泰輝     ﾅｶﾉ ﾀｲｷ  1年      5
149         156    創成Ｍ　理工　化学・修士  6123330029   日向　成綱  ﾋﾕｳｶﾞ ｾﾂﾞﾅ  1年      5
158         165    創成Ｍ　理工　化学・修士  6123330118   萱原　將生  ｶﾔﾊﾗ ｼｮｳｾｲ  1年      5

In [15]:
df.groupby('group').count()

       Unnamed: 0  所属  学生番号  氏名  フリガナ  年次
group
0              45  45    45  45    45  45
1              45  45    45  45    45  45
2              45  45    45  45    45  45
3              45  45    45  45    45  45
4              45  45    45  45    45  45
5              45  45    45  45    45  45
6              45  45    45  45    45  45
7              45  45    45  45    45  45
8              45  45    45  45    45  45

In [ ]:
# divide students into groups whose member are 6 or 7, and  in a group,  '所属' is randomy distributed if possible
# 1. divide students into groups whose member are 6 or 7
# 2. in a group,  '所属' is randomy distributed if possible
# 3. if the number of students is not divisible by 6 or 7, the number of students in a group is 6 or 7 as much as possible
# 4. if the number of students is not divisible by 6 or 7, the number of students in a group is 6 or 7 as much as possible
# 5. if the number of students is not divisible by 6 or 7, the number of students in a group is 6 or 7 as much as possible
# 6. if the number of students is not divisible by 6 or 7, the number of students in a group is 6 or 7 as much as possible